apiVersion: v1                                                                           
kind: ConfigMap                                                                          
metadata:                                                                                
  name: nginx-html                                                                       
data:                                                                                    
 index.html: |                                                                           
    <html><body>Love doing my SCGC Homework!</body></html>  