apiVersion: v1                                                                           
kind: Service                                                                            
metadata:                                                                                
  name: nginx                                                                            
spec:                                                                                    
  type: NodePort                                                                         
  selector:                                                                              
    app: nginx                                                                           
  ports:                                                                                 
    - protocol: TCP                                                                      
      name: index                                                                        
      port: 80                                                                           
      targetPort: 80                                                                     
      nodePort: 30080                                                                    
    - port : 8080                                                                        
      name : metrics                                                                     
      targetPort: 8080                                                                   
      nodePort: 30088 