apiVersion: apps/v1
kind: Deployment
metadata:
  name: promexporter
  labels:
    app.kubernetes.io/name: promexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: promexporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promexporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - -nginx.scrape-uri=http://10.96.172.29:8080/metrics
        ports:
        - containerPort: 9113
